// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerrariaDB.Data;

#nullable disable

namespace TerrariaDB.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211220025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Boss", b =>
                {
                    b.Property<string>("BossName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<short?>("SummonItemId")
                        .HasColumnType("SMALLINT");

                    b.HasKey("BossName");

                    b.HasIndex("SummonItemId")
                        .IsUnique()
                        .HasFilter("[SummonItemId] IS NOT NULL");

                    b.ToTable("Boss");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.BossDrop", b =>
                {
                    b.Property<string>("BossName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<short>("ItemId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Quantity")
                        .HasColumnType("SMALLINT");

                    b.HasKey("BossName", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BossDrop", t =>
                        {
                            t.HasCheckConstraint("CK_BossDrop_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.BossPart", b =>
                {
                    b.Property<short>("BossPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("BossPartId"));

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<short>("HostileEntityId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Quantity")
                        .HasColumnType("SMALLINT");

                    b.HasKey("BossPartId");

                    b.HasIndex("BossName");

                    b.HasIndex("HostileEntityId")
                        .IsUnique();

                    b.ToTable("BossPart", t =>
                        {
                            t.HasCheckConstraint("CK_BossPart_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.BossPartEnemies", b =>
                {
                    b.Property<short>("BossPartId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("EnemyId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Quantity")
                        .HasColumnType("SMALLINT");

                    b.HasKey("BossPartId", "EnemyId");

                    b.HasIndex("EnemyId");

                    b.ToTable("BossPartEnemies", t =>
                        {
                            t.HasCheckConstraint("CK_BossPartEnemies_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.CraftingStation", b =>
                {
                    b.Property<string>("CraftingStationName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("CraftingStationName");

                    b.ToTable("CraftingStation");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.CurrencyType", b =>
                {
                    b.Property<string>("CurrencyName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("CurrencyName");

                    b.ToTable("CurrencyType");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Enemy", b =>
                {
                    b.Property<short>("EnemyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("EnemyId"));

                    b.Property<short>("HostileEntityId")
                        .HasColumnType("SMALLINT");

                    b.HasKey("EnemyId");

                    b.HasIndex("HostileEntityId")
                        .IsUnique();

                    b.ToTable("Enemy");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Entity", b =>
                {
                    b.Property<short>("EntityId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Defense")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("GameObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("Hp")
                        .HasColumnType("INT");

                    b.HasKey("EntityId");

                    b.HasIndex("GameObjectName")
                        .IsUnique();

                    b.ToTable("Entity", t =>
                        {
                            t.HasCheckConstraint("CK_Entity_Defense", "Defense >= 0");

                            t.HasCheckConstraint("CK_Entity_Hp", "Hp >= 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.EntityDrop", b =>
                {
                    b.Property<short>("EntityId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("ItemId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Quantity")
                        .HasColumnType("SMALLINT");

                    b.HasKey("EntityId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("EntityDrop", t =>
                        {
                            t.HasCheckConstraint("CK_EntityDrop_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.GameObject", b =>
                {
                    b.Property<string>("GameObjectName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Sprite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("TransformName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("GameObjectName");

                    b.HasIndex("Sprite")
                        .IsUnique();

                    b.HasIndex("TransformName")
                        .IsUnique()
                        .HasFilter("[TransformName] IS NOT NULL");

                    b.ToTable("GameObject");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.HostileEntity", b =>
                {
                    b.Property<short>("HostileEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("HostileEntityId"));

                    b.Property<short>("ContactDamage")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("EntityId")
                        .HasColumnType("SMALLINT");

                    b.HasKey("HostileEntityId");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("HostileEntity", t =>
                        {
                            t.HasCheckConstraint("CK_HostileEntity_ContactDamage", "ContactDamage >= 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Item", b =>
                {
                    b.Property<short>("ItemId")
                        .HasColumnType("SMALLINT");

                    b.Property<int>("BasePrice")
                        .HasColumnType("INT");

                    b.Property<string>("CraftingStationName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("GameObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("ItemId");

                    b.HasIndex("CraftingStationName");

                    b.HasIndex("CurrencyName");

                    b.HasIndex("GameObjectName")
                        .IsUnique();

                    b.ToTable("Item", t =>
                        {
                            t.HasCheckConstraint("CK_Item_BasePrice", "BasePrice >= 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Recipe", b =>
                {
                    b.Property<short>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("RecipeId"));

                    b.Property<string>("CraftingStationName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<short>("ResultItemId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("ResultItemQuantity")
                        .HasColumnType("SMALLINT");

                    b.HasKey("RecipeId");

                    b.HasIndex("CraftingStationName");

                    b.HasIndex("ResultItemId");

                    b.ToTable("Recipe", t =>
                        {
                            t.HasCheckConstraint("CK_Recipe_ResultItemQuantity", "ResultItemQuantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.RecipeItems", b =>
                {
                    b.Property<short>("RecipeId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("ItemId")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Quantity")
                        .HasColumnType("SMALLINT");

                    b.HasKey("RecipeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("RecipeItems", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeItems_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.TownNpc", b =>
                {
                    b.Property<byte>("TownNpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("TownNpcId"));

                    b.Property<short>("EntityId")
                        .HasColumnType("SMALLINT");

                    b.HasKey("TownNpcId");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("TownNpc");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.TradeOffer", b =>
                {
                    b.Property<short>("ItemId")
                        .HasColumnType("SMALLINT");

                    b.Property<byte>("TownNpcId")
                        .HasColumnType("TINYINT");

                    b.Property<short>("Quantity")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("TradeTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("ItemId", "TownNpcId");

                    b.HasIndex("TownNpcId");

                    b.HasIndex("TradeTypeName");

                    b.ToTable("TradeOffer", t =>
                        {
                            t.HasCheckConstraint("CK_TradeOffer_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.TradeType", b =>
                {
                    b.Property<string>("TradeTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("TradeTypeName");

                    b.ToTable("TradeType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Boss", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Item", "SummonItem")
                        .WithOne("SummonedBoss")
                        .HasForeignKey("TerrariaDB.Models.Terraria.Boss", "SummonItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SummonItem");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.BossDrop", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Boss", "Boss")
                        .WithMany("BossDrops")
                        .HasForeignKey("BossName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.Item", "Item")
                        .WithMany("BossDrops")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boss");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.BossPart", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Boss", "Boss")
                        .WithMany("BossParts")
                        .HasForeignKey("BossName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.HostileEntity", "HostileEntity")
                        .WithOne("BossPart")
                        .HasForeignKey("TerrariaDB.Models.Terraria.BossPart", "HostileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boss");

                    b.Navigation("HostileEntity");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.BossPartEnemies", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.BossPart", "BossPart")
                        .WithMany("BossPartEnemies")
                        .HasForeignKey("BossPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.Enemy", "Enemy")
                        .WithMany("BossPartEnemies")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BossPart");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Enemy", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.HostileEntity", "HostileEntity")
                        .WithOne("Enemy")
                        .HasForeignKey("TerrariaDB.Models.Terraria.Enemy", "HostileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostileEntity");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Entity", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.GameObject", "GameObject")
                        .WithOne("Entity")
                        .HasForeignKey("TerrariaDB.Models.Terraria.Entity", "GameObjectName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameObject");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.EntityDrop", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Entity", "Entity")
                        .WithMany("EntityDrops")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.Item", "Item")
                        .WithMany("EntityDrops")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.GameObject", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.GameObject", "Transform")
                        .WithOne("TransformedFrom")
                        .HasForeignKey("TerrariaDB.Models.Terraria.GameObject", "TransformName")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Transform");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.HostileEntity", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Entity", "Entity")
                        .WithOne("HostileEntity")
                        .HasForeignKey("TerrariaDB.Models.Terraria.HostileEntity", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Item", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.CraftingStation", "CraftingStation")
                        .WithMany("Items")
                        .HasForeignKey("CraftingStationName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TerrariaDB.Models.Terraria.CurrencyType", "CurrencyType")
                        .WithMany("Items")
                        .HasForeignKey("CurrencyName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.GameObject", "GameObject")
                        .WithOne("Item")
                        .HasForeignKey("TerrariaDB.Models.Terraria.Item", "GameObjectName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CraftingStation");

                    b.Navigation("CurrencyType");

                    b.Navigation("GameObject");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Recipe", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.CraftingStation", "CraftingStation")
                        .WithMany("Recipes")
                        .HasForeignKey("CraftingStationName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TerrariaDB.Models.Terraria.Item", "ResultItem")
                        .WithMany("ResultRecipes")
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CraftingStation");

                    b.Navigation("ResultItem");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.RecipeItems", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Item", "Item")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.Recipe", "Recipe")
                        .WithMany("RecipeItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.TownNpc", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Entity", "Entity")
                        .WithOne("TownNpc")
                        .HasForeignKey("TerrariaDB.Models.Terraria.TownNpc", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.TradeOffer", b =>
                {
                    b.HasOne("TerrariaDB.Models.Terraria.Item", "Item")
                        .WithMany("TradeOffers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.TownNpc", "TownNpc")
                        .WithMany("TradeOffers")
                        .HasForeignKey("TownNpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaDB.Models.Terraria.TradeType", "TradeType")
                        .WithMany("TradeOffers")
                        .HasForeignKey("TradeTypeName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("TownNpc");

                    b.Navigation("TradeType");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Boss", b =>
                {
                    b.Navigation("BossDrops");

                    b.Navigation("BossParts");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.BossPart", b =>
                {
                    b.Navigation("BossPartEnemies");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.CraftingStation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.CurrencyType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Enemy", b =>
                {
                    b.Navigation("BossPartEnemies");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Entity", b =>
                {
                    b.Navigation("EntityDrops");

                    b.Navigation("HostileEntity");

                    b.Navigation("TownNpc");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.GameObject", b =>
                {
                    b.Navigation("Entity");

                    b.Navigation("Item");

                    b.Navigation("TransformedFrom");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.HostileEntity", b =>
                {
                    b.Navigation("BossPart");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Item", b =>
                {
                    b.Navigation("BossDrops");

                    b.Navigation("EntityDrops");

                    b.Navigation("RecipeItems");

                    b.Navigation("ResultRecipes");

                    b.Navigation("SummonedBoss");

                    b.Navigation("TradeOffers");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.Recipe", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.TownNpc", b =>
                {
                    b.Navigation("TradeOffers");
                });

            modelBuilder.Entity("TerrariaDB.Models.Terraria.TradeType", b =>
                {
                    b.Navigation("TradeOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
