// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerrariaCompendium.Data;

#nullable disable

namespace TerrariaCompendium.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Boss", b =>
                {
                    b.Property<int>("BossId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BossId"));

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BossSprite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SummonItemId")
                        .HasColumnType("int");

                    b.HasKey("BossId");

                    b.HasIndex("BossName")
                        .IsUnique();

                    b.HasIndex("BossSprite")
                        .IsUnique();

                    b.HasIndex("SummonItemId")
                        .IsUnique()
                        .HasFilter("[SummonItemId] IS NOT NULL");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossDrop", b =>
                {
                    b.Property<int>("BossDropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BossDropId"));

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("BossDropId");

                    b.HasIndex("BossId");

                    b.HasIndex("ItemId");

                    b.ToTable("BossDrops", t =>
                        {
                            t.HasCheckConstraint("CK_BossDrop_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPart", b =>
                {
                    b.Property<int>("BossPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BossPartId"));

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<short>("BossPartOrderId")
                        .HasColumnType("smallint");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("BossPartId");

                    b.HasIndex("BossId");

                    b.HasIndex("BossPartOrderId")
                        .IsUnique();

                    b.HasIndex("EntityId");

                    b.ToTable("BossParts", t =>
                        {
                            t.HasCheckConstraint("CK_BossPart_BossPartOrderId", "BossPartOrderId >= 0 AND BossPartOrderId <= 5");

                            t.HasCheckConstraint("CK_BossPart_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPartStage", b =>
                {
                    b.Property<int>("BossPartStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BossPartStageId"));

                    b.Property<int>("BossPartId")
                        .HasColumnType("int");

                    b.Property<short>("BossPartStageOrderId")
                        .HasColumnType("smallint");

                    b.Property<string>("BossPartStageSprite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short>("ContactDamage")
                        .HasColumnType("smallint");

                    b.Property<short>("Defense")
                        .HasColumnType("smallint");

                    b.Property<short>("Hp")
                        .HasColumnType("smallint");

                    b.HasKey("BossPartStageId");

                    b.HasIndex("BossPartId");

                    b.HasIndex("BossPartStageOrderId")
                        .IsUnique();

                    b.ToTable("BossPartStages", t =>
                        {
                            t.HasCheckConstraint("CK_BossPartStage_BossPartStageOrderId", "BossPartStageOrderId >= 0 AND BossPartStageOrderId <= 3");

                            t.HasCheckConstraint("CK_BossPartStage_ContactDamage", "ContactDamage >= 0");

                            t.HasCheckConstraint("CK_BossPartStage_Defense", "Defense >= 0");

                            t.HasCheckConstraint("CK_BossPartStage_Hp", "Hp >= 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPartStageEnemies", b =>
                {
                    b.Property<int>("BossPartStageEnemiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BossPartStageEnemiesId"));

                    b.Property<int>("BossPartStageId")
                        .HasColumnType("int");

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("BossPartStageEnemiesId");

                    b.HasIndex("BossPartStageId");

                    b.HasIndex("EnemyId");

                    b.ToTable("BossPartStageEnemies", t =>
                        {
                            t.HasCheckConstraint("CK_BossPartStageEnemies_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.CraftingStation", b =>
                {
                    b.Property<int>("CraftingStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CraftingStationId"));

                    b.Property<string>("CraftingStationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CraftingStationSprite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CraftingStationId");

                    b.HasIndex("CraftingStationName")
                        .IsUnique();

                    b.HasIndex("CraftingStationSprite")
                        .IsUnique();

                    b.ToTable("CraftingStations");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Enemy", b =>
                {
                    b.Property<int>("EnemyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnemyId"));

                    b.Property<short>("ContactDamage")
                        .HasColumnType("smallint");

                    b.Property<short>("Defense")
                        .HasColumnType("smallint");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<short>("Hp")
                        .HasColumnType("smallint");

                    b.HasKey("EnemyId");

                    b.HasIndex("EntityId");

                    b.ToTable("Enemies", t =>
                        {
                            t.HasCheckConstraint("CK_Enemy_ContactDamage", "ContactDamage >= 0");

                            t.HasCheckConstraint("CK_Enemy_Defense", "Defense >= 0");

                            t.HasCheckConstraint("CK_Enemy_Hp", "Hp >= 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Entity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("InternalNpcId")
                        .HasColumnType("smallint");

                    b.HasKey("EntityId");

                    b.HasIndex("InternalNpcId")
                        .IsUnique();

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.EntityDrop", b =>
                {
                    b.Property<int>("EntityDropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityDropId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("EntityDropId");

                    b.HasIndex("EntityId");

                    b.HasIndex("ItemId");

                    b.ToTable("EntityDrops", t =>
                        {
                            t.HasCheckConstraint("CK_EntityDrop_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("BuyPriceCurrency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CraftingStationId")
                        .HasColumnType("int");

                    b.Property<short>("InternalItemId")
                        .HasColumnType("smallint");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("CraftingStationId");

                    b.HasIndex("InternalItemId")
                        .IsUnique();

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.ToTable("Items", t =>
                        {
                            t.HasCheckConstraint("CK_Item_BuyPrice", "BuyPrice >= 0");

                            t.HasCheckConstraint("CK_Item_SellPrice", "SellPrice >= 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.ItemForm", b =>
                {
                    b.Property<int>("ItemFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemFormId"));

                    b.Property<short>("ItemFormOrderId")
                        .HasColumnType("smallint");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemSprite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ItemFormId");

                    b.HasIndex("ItemFormOrderId")
                        .IsUnique();

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemSprite")
                        .IsUnique();

                    b.ToTable("ItemForms", t =>
                        {
                            t.HasCheckConstraint("CK_ItemForm_ItemFormOrderId", "ItemFormOrderId >= 0 AND ItemFormOrderId <= 4");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("CraftingStationId")
                        .HasColumnType("int");

                    b.Property<int>("ResultItemId")
                        .HasColumnType("int");

                    b.Property<short>("ResultItemQuantity")
                        .HasColumnType("smallint");

                    b.HasKey("RecipeId");

                    b.HasIndex("CraftingStationId");

                    b.HasIndex("ResultItemId");

                    b.ToTable("Recipes", t =>
                        {
                            t.HasCheckConstraint("CK_Recipe_ResultItemQuantity", "ResultItemQuantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.RecipeItems", b =>
                {
                    b.Property<int>("RecipeItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeItemsId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeItemsId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeItems", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeItems_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.TownNpc", b =>
                {
                    b.Property<int>("TownNpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TownNpcId"));

                    b.Property<short>("Defense")
                        .HasColumnType("smallint");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<short>("Hp")
                        .HasColumnType("smallint");

                    b.HasKey("TownNpcId");

                    b.HasIndex("EntityId");

                    b.ToTable("TownNpc", t =>
                        {
                            t.HasCheckConstraint("CK_TownNpc_Defense", "Defense >= 0");

                            t.HasCheckConstraint("CK_TownNpc_Hp", "Hp >= 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.TownNpcForm", b =>
                {
                    b.Property<int>("TownNpcFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TownNpcFormId"));

                    b.Property<short>("TownNpcFormOrderId")
                        .HasColumnType("smallint");

                    b.Property<string>("TownNpcFormSprite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TownNpcId")
                        .HasColumnType("int");

                    b.HasKey("TownNpcFormId");

                    b.HasIndex("TownNpcFormOrderId")
                        .IsUnique();

                    b.HasIndex("TownNpcFormSprite")
                        .IsUnique();

                    b.HasIndex("TownNpcId");

                    b.ToTable("TownNpcForms", t =>
                        {
                            t.HasCheckConstraint("CK_TownNpcForm_TownNpcFormOrderId", "TownNpcFormOrderId >= 0 AND TownNpcFormOrderId <= 4");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.TradeOffer", b =>
                {
                    b.Property<int>("TradeOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeOfferId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<int>("TownNpcId")
                        .HasColumnType("int");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TradeOfferId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TownNpcId");

                    b.ToTable("TradeOffers", t =>
                        {
                            t.HasCheckConstraint("CK_TradeOffer_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Boss", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Item", "SummonItem")
                        .WithOne("SummonedBoss")
                        .HasForeignKey("TerrariaCompendium.Models.Terraria.Boss", "SummonItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SummonItem");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossDrop", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Boss", "Boss")
                        .WithMany("BossDrops")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaCompendium.Models.Terraria.Item", "Item")
                        .WithMany("BossDrops")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boss");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPart", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Boss", "Boss")
                        .WithMany("BossParts")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaCompendium.Models.Terraria.Entity", "Entity")
                        .WithMany("BossParts")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boss");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPartStage", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.BossPart", "BossPart")
                        .WithMany("BossPartStages")
                        .HasForeignKey("BossPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BossPart");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPartStageEnemies", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.BossPartStage", "BossPartStage")
                        .WithMany("BossPartStageEnemies")
                        .HasForeignKey("BossPartStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaCompendium.Models.Terraria.Enemy", "Enemy")
                        .WithMany("BossPartStageEnemies")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BossPartStage");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Enemy", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Entity", "Entity")
                        .WithMany("Enemies")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.EntityDrop", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Entity", "Entity")
                        .WithMany("EntityDrops")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerrariaCompendium.Models.Terraria.Item", "Item")
                        .WithMany("EntityDrops")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Item", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.CraftingStation", "CraftingStation")
                        .WithMany("Items")
                        .HasForeignKey("CraftingStationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CraftingStation");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.ItemForm", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Item", "Item")
                        .WithMany("ItemForms")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Recipe", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.CraftingStation", "CraftingStation")
                        .WithMany("Recipes")
                        .HasForeignKey("CraftingStationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TerrariaCompendium.Models.Terraria.Item", "ResultItem")
                        .WithMany("Recipes")
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CraftingStation");

                    b.Navigation("ResultItem");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.RecipeItems", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Item", "Item")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerrariaCompendium.Models.Terraria.Recipe", "Recipe")
                        .WithMany("RecipeItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.TownNpc", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Entity", "Entity")
                        .WithMany("TownNpcs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.TownNpcForm", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.TownNpc", "TownNpc")
                        .WithMany("TownNpcForms")
                        .HasForeignKey("TownNpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TownNpc");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.TradeOffer", b =>
                {
                    b.HasOne("TerrariaCompendium.Models.Terraria.Item", "Item")
                        .WithMany("TradeOffers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerrariaCompendium.Models.Terraria.TownNpc", "TownNpc")
                        .WithMany("TradeOffers")
                        .HasForeignKey("TownNpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("TownNpc");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Boss", b =>
                {
                    b.Navigation("BossDrops");

                    b.Navigation("BossParts");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPart", b =>
                {
                    b.Navigation("BossPartStages");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.BossPartStage", b =>
                {
                    b.Navigation("BossPartStageEnemies");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.CraftingStation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Enemy", b =>
                {
                    b.Navigation("BossPartStageEnemies");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Entity", b =>
                {
                    b.Navigation("BossParts");

                    b.Navigation("Enemies");

                    b.Navigation("EntityDrops");

                    b.Navigation("TownNpcs");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Item", b =>
                {
                    b.Navigation("BossDrops");

                    b.Navigation("EntityDrops");

                    b.Navigation("ItemForms");

                    b.Navigation("RecipeItems");

                    b.Navigation("Recipes");

                    b.Navigation("SummonedBoss");

                    b.Navigation("TradeOffers");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.Recipe", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("TerrariaCompendium.Models.Terraria.TownNpc", b =>
                {
                    b.Navigation("TownNpcForms");

                    b.Navigation("TradeOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
